### ISSUE TITLE
Админский модуль последнийх заказов

### ISSUE THREAD

**Issue by Septdir** [Joomline/contentcart#1]
Думаю не помешал бы модуль для главной страницы панели администрирования.

Пишется такой модуль быстро, а удобства прибавляет прилично. Особенно в маленьких шопах где макс. 10-15 активных заказов, они все будут сразу на виду и не придется лезть в com_content

**Comment by zikkuratvk** [comment]
А смысл? по сути это модуль последних статей для админки. 
Заходишь в настройки модуля последних материалов или создаешь копию его и выбираешь настройки категорию. https://s.mail.ru/A7GT/txmM1Urzo

**Comment by Septdir** [comment]
Суть во внешке и в том что не нужно выбирать категорию.

Конечно можно сделать самому переопределение. Создать отдельный модуль, выставить настройки и т.д.

Но суть отдельное модуля - это поставил пакет и все работает.

**Comment by zikkuratvk** [comment]
В том то весь и прикол этот модуль уже есть в Joomla и ничего переопределять не нужно, просто настроить категорию из какой выводить материалы.

**Comment by Septdir** [comment]
А там выводиться сумма заказа? Данные клиента и т.д.

Убеждать в необходимости не буду. Просто ИМХО удобный модуль заказов нужен

**Comment by zikkuratvk** [comment]
А там ты сумму заказа не выведешь хотя конечно можно попробовать :-)

**Comment by Septdir** [comment]
Нет ничего невозможного =)
