### ISSUE TITLE
joomla 4 не корректно создаются материалы с заказами

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/contentcart#3]
При включенной опции сохранения заказов в материалах Joomla такие настройки.
![image](https://user-images.githubusercontent.com/2261206/201640470-cc61ac5b-25bb-45bf-87c5-d3a48d29d6bd.png)
Материалы создаются не корректно, они присутствуют в базе, но не выводятся в админке joomla.

![image](https://user-images.githubusercontent.com/2261206/201640648-21430c49-c3cf-47dd-ae1f-6e6e58600e1f.png)

**Comment by Arkadiy-Sedelnikov** [comment]
А почему статья должна быть в категории "Заказы"? Скорее всего она в другой категории. Я создал свою статью, поместил в категоию "Заказы" и вуаля: 
![изображение](https://user-images.githubusercontent.com/1139656/202213805-f7aed1cc-90fd-4060-8280-726d29b652c6.png)

**Comment by zikkuratvk** [comment]
Потому что по логике настроек, если заказ создан то в этой категории создается материал с параметрами заказа. То есть это своеобразный лог заказов, которые не просто отправляются на почту, а создается материал, в описании которого содержится состав заказа.

Если из категории Joomla посмотреть. То мы даже счетчик этих материалов видим, как создается.

![image](https://user-images.githubusercontent.com/2261206/202215346-5b7bf10d-0691-4e16-8f24-5b4d4c01aa4a.png)
