### ISSUE TITLE
При переходе в корзину на Joomla 3 ошибка

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/contentcart#5]
![image](https://user-images.githubusercontent.com/2261206/201641243-f262d181-2b67-4a3d-a051-f21e20becd1d.png)

Ошибка: 0 Call to undefined method Joomla\CMS\Application\SiteApplication::bootComponent()

Дальнейшее тестирование плагина под Joomla 3 не представляется возможным.

http://[demo3.joomline.ru/comcontent/18-test3-3?cart=1](http://demo3.joomline.ru/comcontent/18-test3-3?cart=1) - пример ссылки

**Comment by Arkadiy-Sedelnikov** [comment]
А какой смысл на тройку этот плагин точить? На тройке есть рабочая версия, пусть с ней и умирает. Наигрался уже с совместимостью на слогине.
